name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT CODE
      uses: actions/checkout@v4

    - name: SET UP GO
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: RUN LINTER
      run: make lint

  build:
    runs-on: ubuntu-latest
    needs: linter
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0 
        fetch-tags: true 

    - name: SET UP GO
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: BUILD
      run: make image_linux

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: PUSH DOCKER IMAGE
      run: make push_linux 

  cd:
    name: CD
    needs: ['linter', 'build']
    runs-on: ubuntu-latest
    permissions:
      contents: write 
 
    steps:
     - name: CHECKOUT CODE
       uses: actions/checkout@v4
       with: 
         fetch-depth: 0 
         fetch-tags: true
   
     - name: DECLARE VARIABLES
       id: vars
       shell: bash
       run: |
         echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
         echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
   
     - name: Update current version
       uses: mikefarah/yq@3.3.2
       with: 
         cmd: yq w -i helm/values.yaml image.tag ${{ steps.vars.outputs.tag }}-${{ steps.vars.outputs.sha_short }}
        
     - name: SETUP GIT CONFIG
       run: |
         git config user.name "GitHub Actions"
         git config user.email "<>"
         git add helm/values.yaml
         git commit -m "update code version to ${{ steps.vars.outputs.sha_short }}"
     
     - name: PUSH CHANGES
       uses: ad-m/github-push-action@master
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: develop    