name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: SET UP GO
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: RUN LINTER
      run: make lint

  build:
    runs-on: ubuntu-latest
    needs: linter
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0 
        fetch-tags: true 

    - name: SET UP GO
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: BUILD
      run: make image_linux 
      env:
        TELE_TOKEN: ${{ secrets.TELE_TOKEN }}

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: PUSH DOCKER IMAGE
      run: make push_linux 