name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: SET UP GO
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: RUN LINTER
      run: make lint

  build:
    runs-on: ubuntu-latest
    needs: linter
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0 
        fetch-tags: true 

    - name: SET UP GO
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: BUILD
      run: make image_linux 

    - name: PUSH DOCKER IMAGE
      run: make push_linux 